apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "humrefarch-njs-04"
  annotations:
    "humanitec.com/orgId": "migfe-explore"
    "humanitec.com/appId": "humrefarch-njs-04"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
